// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_5J6jhPJAu_ioSjKdaUJMnbusHwM-tt0',
    appId: '1:1075012183569:web:4109a90913310e398073b0',
    messagingSenderId: '1075012183569',
    projectId: 'plastic-bounty',
    authDomain: 'plastic-bounty.firebaseapp.com',
    storageBucket: 'plastic-bounty.appspot.com',
    measurementId: 'G-18Q5ETM3K9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9DVCI907CtjdXcf2FC6OkNW1KWLmHTDk',
    appId: '1:1075012183569:android:9cfc75f2d1a8983a8073b0',
    messagingSenderId: '1075012183569',
    projectId: 'plastic-bounty',
    storageBucket: 'plastic-bounty.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClngrwBna1yC1H2qGvC26B-kJ2U1A9gYg',
    appId: '1:1075012183569:ios:b2ca6e0729d6cdc58073b0',
    messagingSenderId: '1075012183569',
    projectId: 'plastic-bounty',
    storageBucket: 'plastic-bounty.appspot.com',
    iosClientId: '1075012183569-m2h35m6pnrsnimt22f6pg4170e7h7lmp.apps.googleusercontent.com',
    iosBundleId: 'com.example.plasticBounty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClngrwBna1yC1H2qGvC26B-kJ2U1A9gYg',
    appId: '1:1075012183569:ios:adb5b9afb46c06748073b0',
    messagingSenderId: '1075012183569',
    projectId: 'plastic-bounty',
    storageBucket: 'plastic-bounty.appspot.com',
    iosClientId: '1075012183569-4ibdhl7sj4sf2rivegohku9c9843irbv.apps.googleusercontent.com',
    iosBundleId: 'com.example.plasticBounty.RunnerTests',
  );
}
